//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 09:58:28 PM CEST 
//


package utafx.ui.pref.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for criteriaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="criteriaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="gain"/>
 *     &lt;enumeration value="cost"/>
 *     &lt;enumeration value="ordinal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "criteriaType")
@XmlEnum
public enum CriteriaType {

    @XmlEnumValue("gain")
    GAIN("gain"),
    @XmlEnumValue("cost")
    COST("cost"),
    @XmlEnumValue("ordinal")
    ORDINAL("ordinal");
    private final String value;

    CriteriaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CriteriaType fromValue(String v) {
        for (CriteriaType c: CriteriaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
