//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 09:58:28 PM CEST 
//


package utafx.ui.pref.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pref.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Preferences_QNAME = new QName("", "preferences");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pref.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Alternative }
     * 
     */
    public Alternative createAlternative() {
        return new Alternative();
    }

    /**
     * Create an instance of {@link Criteria }
     * 
     */
    public Criteria createCriteria() {
        return new Criteria();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link Ordinals }
     * 
     */
    public Ordinals createOrdinals() {
        return new Ordinals();
    }

    /**
     * Create an instance of {@link Criterion }
     * 
     */
    public Criterion createCriterion() {
        return new Criterion();
    }

    /**
     * Create an instance of {@link RefRank }
     * 
     */
    public RefRank createRefRank() {
        return new RefRank();
    }

    /**
     * Create an instance of {@link Ordinal }
     * 
     */
    public Ordinal createOrdinal() {
        return new Ordinal();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link RrItem }
     * 
     */
    public RrItem createRrItem() {
        return new RrItem();
    }

    /**
     * Create an instance of {@link Alternatives }
     * 
     */
    public Alternatives createAlternatives() {
        return new Alternatives();
    }

    /**
     * Create an instance of {@link AltValues }
     * 
     */
    public AltValues createAltValues() {
        return new AltValues();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Preferences }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "preferences")
    public JAXBElement<Preferences> createPreferences(Preferences value) {
        return new JAXBElement<Preferences>(_Preferences_QNAME, Preferences.class, null, value);
    }

}
